### ISSUE TITLE
False positive issue

### ISSUE THREAD

**Issue by doobidoob** [andy-yun/pytorch-0.4-yolov3#11]
Hi, thanks for providing the code.
Your implementation seems to be the best among Yolov3-pytorch version in github.
I experimented with the code, and I have a few questions.

After training with my data, there is a false positive issue in inference. (I only changed the dataset.)
For example, there is a problem that boxes overlap on small objects and some boxes aren't accurate.
It is expected that there is a problem in the training process through the fact that there is no big problem in inference with using the author's weight.

I'm trying to solve this problem. but it's not easy.
Do you know where this problem occurs in the code?
If you can afford it, I would like you to consider this problem together.
Thank you.

**Comment by andy-yun** [comment]
Maybe they are related to build target (region_layer.py and yolo_layer.py) especially coord_mask and conf_mask. These parts are some different with original version.  Unfortunately, nowadays, I have no lots of time to inspect the problem. T_T

**Comment by lianuo** [comment]
@doobidoob have you solve it?

**Comment by andy-yun** [comment]
Did you update the anchor box information based on your data at your cfg file ?
Those information can be found at [yolo] sections in cfg file.

**Comment by doobidoob** [comment]
@andy-yun Yeah, I already know that, thanks. But in original YOLOv3 implememted by C, theres's no problem in my own dataset, even though no change in cfg file except class number and outputs. 
Have you ever trained and experimented with COCO data?
How much is the mAP performance?
(The performance of the YOLOv3 paper is 0.57 mAP.)
When I experimented with COCO data with yours, I got a 0.36 mAP when I was training 80 epochs in 8 batch sizes.
(If i increase the batch size in my server environment, it accurs CUDU memory error, so I set batch size 8.)

@lianuo No.... I have not solved it yet.

**Comment by lianuo** [comment]
@doobidoob could you share the predict image result ? 
I plan to train with my own data too.Thank you

**Comment by andy-yun** [comment]
@doobidoob I downloaded COCO data and am started to train in ubuntu 16.04 machine with two 1080Ti.
In my opinion, you cannot get sufficient result on 80 epoch numbers. I tested my own data, at lease over 200 epoch, I can get the meaningful results. 
Anyway, I will post the mAP for COCO data for over 200 epochs. I trained my own data using original darknet C module and my pytorch version. Fortunately, both results are very similar to each other.
But, the batch and subdivision are different for linux and windows 10 version, the saturation time is different.

**Comment by andy-yun** [comment]
@doobidoob If you want to training over max epoch that is automatically decided, you can add max_epochs in [net] section of your cfgfile.

**Comment by jjeonda** [comment]
Hi. 
Now I'm testing your code with coco dataset.
And I got the error about OOM(cuda out of memory errror).
![image](https://user-images.githubusercontent.com/35592964/45276043-0e080e00-b4fb-11e8-84b2-aca87f15ec7f.png)
I tried training around 30 epochs (max_batch 500200), but it always ends with upper error.
cfg file not obtain max_epoch. 
Also your code, train.py , calculates max_epoch as max_batches.
I think about kind of pytorch graph issue (https://discuss.pytorch.org/t/cuda-memory-continuously-increases-when-net-images-called-in-every-iteration/501 , I tried .detach() but not working)
Please give me some advise about this error.
Thank you :)

**Comment by andy-yun** [comment]
You sould decrease batch in [net] of your cfg file.
For example, batch=64 to batch=32 or 16.

In my machine, at first, I did train with batch=32, but after 10 epochs, OOM error occurred. 
Thus, I decreased batch to 16. Still, there is not enough space. I wonder when OOM error occurrs.

**Comment by andy-yun** [comment]
@doobidoob @lianuo I explained in another issue why my version shows the lower performance than the original C version. That is the image resize method without keeping width height ratio. If the object is small, object modeling without keeping width/height ratio absolutely shows lower performance. I will fix them in near future. Thanks.

**Comment by doobidoob** [comment]
@andy-yun Thanks! I see. 
Does that mean that the resize part should be fixed in the training process too?
In order to achieve similar performance to the original code about training rather than the inference, the resize part seems to have to be fixed.

**Comment by doobidoob** [comment]
@andy-yun I checked the original C code how to resize the image in training process.
In training, image proportion (width and height ratio) is not preserved in resize part.
In inference, image proportion is preserved as you said.
Thanks.

**Comment by andy-yun** [comment]
@doobidoob Yup, in the origian C code and pytorch version, data augmented randomly and not keep the width height ratio. But, in evaluation mode, the original C version resized the input image with preserving the width height ratio. The images are just scaled to network size in my version and marvis version. And some weakness is found at data augmentation module. I modified the module but not yet tested since  I am testing voco data set with changed conf_mask weights. I will uploaded code as soon as possible after finishing some test.

**Comment by doobidoob** [comment]
@andy-yun Hi. Can you share your experimental results so far?
I want to make it similar to original author performance, but it is very difficult.

Please note the contents of my experiment below.
#22 

Thanks.

**Comment by andy-yun** [comment]
@doobidoob I did several experiment along to various weights to loss. Nowadays, I performed yolov2 experiment and yolov3 simultaneously. 

My experiments are modified as follows:
1. adjust weights of losses (boxes, confidence, classes)
2. modify data augmentation module and target images with keeping width/height ratio.

Unfortunately, when I trained the model with 200 epochs for COCO dataset without the above adjustments. It shows just about 40 mAP. Still, I am testing model with both modifications as I mentioned in the above statements for voc and coco datasets.

after that, I will compare the mse and bce loss functions. In my knowledge, bce requires the output to be in the range of 0 and 1. This means that bce requires the sigmoid outputs. If you don't want to use sigmoid, you should use bcewithlogitsloss function.

If I get the meaningful results, I will update the code. Thanks.

**Comment by andy-yun** [comment]
@doobidoob I fixed some bugs and modified handling module, data augmentation of input image for test. Here are some results for different scales. The experiments are done for voc datasets with yolo v2.

coord_scale=1, object_scale=5, class_scale=1 mAP = 73.1 (original yolo-voc.cfg)
coord_scale=1, object_scale=5, class_scale=2 mAP = 72.7
coord_scale=1, object_scale=3, class_scale=1 mAP = 73.4 (best)
coord_scale=1, object_scale=3, class_scale=2 mAP = 72.8
coord_scale=1, object_scale=1, class_scale=1 mAP = 50.4

**Comment by doobidoob** [comment]
@andy-yun Thank you for sharing your results.
Can you share the results of YOLOv3 for COCO dataset?
I wonder if the performance of YOLOv3_pytorch (yours) is equivalent to the original author's performance.
Thank you very much!

**Comment by andy-yun** [comment]
Currently, with 80 eochs, 45.9 mAP is obtained with latest code. if you do train more than 80, I guess about 50% mAP may be obtained (I am not sure). Therefore, if you want to more accurate training results, I recommend to use original C codes.
