### ISSUE TITLE
About the net

### ISSUE THREAD

**Issue by door5719** [andy-yun/pytorch-0.4-yolov3#13]
Sir ,I want to know the out part of last layer 13x13x255 /26x26x255 /52x52x255(80 classes)..255 may mean Xx3|Yx3|Wx3|Hx3|confidencex3|classesx3 or (X|Y|W|H|confidence|classes)x3,which order is right?

**Comment by andy-yun** [comment]
Does 3 means mask number on detection layer?

each object has a information related to x, y, w, h, classes. Therefore, I think, if I correctly understand your question, the later is right.

**Comment by door5719** [comment]
Thank you very much ,sir~
