### ISSUE TITLE
Performance with gtx1080ti

### ISSUE THREAD

**Issue by ghost** [andy-yun/pytorch-0.4-yolov3#14]
Hi i am training my custom dataset with this yolov3 implementation on a gtx1080ti.

And i have 3 questions:

1. What is the biggest batch size for this network? i have a batchsize of 16 otherwise the vram isnt enough

2. When i train the network the workload of the graphiccard is only at 20%. Is that normal?

3. How many iterations does it normally take until the model converge.

thank you in advance
Stefan

**Comment by andy-yun** [comment]
1. depends on your dataset and computing environments. Therefore, you should try the combination of batchsize and subdivisions.
2. That's normal. In my environments, the workload of GPU is always under 20%. The important thing is the amount of GPU memory.
3. I don't know. But, when the model is trained for about 1,000 epochs, it is sufficient to check your model and data. You should check the testing performance for every iteration and stop the training.
