### ISSUE TITLE
About the trained result

### ISSUE THREAD

**Issue by lianuo** [andy-yun/pytorch-0.4-yolov3#15]
@andy-yun ,Thank you for give such a good option of using YOLOv3 in Pytorch

I have test many others pytorch YOLOv3 training solution, They usually have similar problem when predict a image .
So could you share a weight or detect result with your trained model. 
Thank you ~!

**Comment by andy-yun** [comment]
@lianuo after the training of COCO data, I will post trained model.

**Comment by lianuo** [comment]
@andy-yun HI，Andy, I have trained your code with my data ,the result is better than all other pytorch version yolov3 in GitHub.

I use transfer learning from original weight, and modify the class number.
Freeze other layers weights expect the layers related to the class number.

after training for just few epoch ,such as 20 or fewer, It is converged to a ideal weight, which could detect what I want.

thank you so much~
