### ISSUE TITLE
 param about initial weights

### ISSUE THREAD

**Issue by door5719** [andy-yun/pytorch-0.4-yolov3#21]
sir ,I want to know:
python train.py -d cfg/coco.data -c cfg/yolo_v3.cfg -w yolov3.weights

-w   means  initial weights?

How can I train model without initial weights?
Thank you sir~

**Comment by andy-yun** [comment]
sure. -w means the weights.
In nowadays, the data increase. Therefore, many alogorithm uses initial weights for training.
In yolo model. darknet19_448.conv.23 and darknet53.conv.74 are used for initial weights of yolov2 and yolov3, respectively.

These files are the pretrained weights for imagenet. you can download as follows.
wget https://pjreddie.com/media/files/darknet19_448.conv.23
wget https://pjreddie.com/media/files/darknet53.conv.74

**Comment by door5719** [comment]
Thank you sir for your reply. I want to train model without pre-trained weights ,random initial weights instead.

**Comment by door5719** [comment]
I want to get a effective weights file of yolov3(coco_dateset80class), about how many epoch times will generate the weights file at least.

**Comment by andy-yun** [comment]
@door5719 I don't know. It may be necessary an analysis of training errors and validation performance. See https://github.com/AlexeyAB/darknet

**Comment by door5719** [comment]
Thank you sir.
