### ISSUE TITLE
Multi-GPUs setting

### ISSUE THREAD

**Issue by jaelim** [andy-yun/pytorch-0.4-yolov3#23]
Hello, I'm testing out VOC example. In the voc.data config file in the last line specifies the number of GPUs to use. I use the default setting, but nonetheless upon starting training, I notice that all my GPU cards were in used (I have 8 cards). I want to understand why it is that the config file is not configuring the training setting? I tried to utilize 1 GPU, but still training launches on all available cards.

**Comment by andy-yun** [comment]
I tried to use one GPU on my environment. It works.  Please tell me your environment.
I tested on ubuntu 16.04 version.

**Comment by jaelim** [comment]
RHEL environment. I found out I need to add this in the beginning before python command. So it works now.

`CUDA_VISIBLE_DEVICES=0,1,2`

**Comment by andy-yun** [comment]
@jaelim the above environment variable is automatically assigned in the train.py by reading yolo-voc.data. please check them.
