### ISSUE TITLE
Saving model weights

### ISSUE THREAD

**Issue by jaelim** [andy-yun/pytorch-0.4-yolov3#24]
Hi,

I have a couple questions about variables, `keep_backup` and `old_wgts` in

![image](https://user-images.githubusercontent.com/7217547/46372351-bb27ff00-c63f-11e8-8e81-58c2b28c4013.png)

I needed to modify the default `save_interval = 5` to 1 epoch, so I wasn't sure how to update default `keep_backup = 5`? Do I change it to 1 as well and what's the purpose of `old_wgts`?

**Comment by andy-yun** [comment]
Old_wgts points the file to be deleted. Every weight file is about 200 mbytes. Therefore, if you don not delete old files, may be you suffered out of space in your disk.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by andy-yun** [comment]
Keep_backup means the number of weight files will be saved. And save_interval indicates the interval saving weights. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jaelim** [comment]
I commented out lines to disable the interval weight saving, since my training is only a few epochs.
