### ISSUE TITLE
CUDA out of memory error during training

### ISSUE THREAD

**Issue by bruno-ichec** [andy-yun/pytorch-0.4-yolov3#25]
Hi,

I'm training a model on my own data, on a dual GPU system, Python 3.6, Pytorch 0.4.1, both from Anaconda. Everything is fine for a while: config was adapted to single class model, both GPUs get used properly, batch size of 48 with 2 subdivisions result in 12GB memory usage out of 16GB on each GPU, and the model slowly converges over iterations. However, after a number of iterations (different each time, but somewhere between 1300 and 1500), the training crashes and can't resume as is, with a CUDA out of memory error.

> Traceback (most recent call last):
>   File "train.py", line 362, in <module>
>     main()
>   File "train.py", line 152, in main
>     nsamples = train(epoch)
>   File "train.py", line 242, in train
>     sum(org_loss).backward()
>   File "/home/bruno/anaconda/envs/pytorch/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
>     torch.autograd.backward(self, gradient, retain_graph, create_graph)
>   File "/home/bruno/anaconda/envs/pytorch/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
>     allow_unreachable=True)  # allow_unreachable flag
> RuntimeError: CUDA error: out of memory

From there, my only option to resume training from checkpoint is to reduce the batch size to about a single image per GPU per iteration, anything else saturates at least one GPU (the second one seems to increase its memory usage and crash first, but maybe that'd happen too on the first one given time).

I thought increasing subdivisions would help, and ultimately that having subdivisions == batch size would have as low a memory footprint as possible, but that still produces the error, which only goes away with a tiny batch size.

I tried setting "random=0" in the config as if I understand correctly, that disables the random resizing of the net, which could make the memory usage vary, but the error happens again around the same number of iterations when I expected it to remain constant over time.

I assume there's something I'm doing wrong or missing in the YOLO configuration but not sure what. Any ideas?

**Comment by jaelim** [comment]
@bruno-ichec I also had the similar experience. So, essentially you reduced batch numbers from 48 to 1 to avoid out-of-memory error?

**Comment by bruno-ichec** [comment]
@jaelim The exact number depends on the case but yeah, I have to try and reduce the batch size until it fits again, and it's a considerable difference. In this particular case, after the OOM on iteration 1316 (batch size 48, subdivisions 2), I could get away with a batch size of 16 (2 subdivisions). That's on a dual-GPU node, so 8 images per GPU per mini-batch. I've had a case where I had to go down to a batch size of 2 (with 2 subdivisions).

**Comment by bruno-ichec** [comment]
Errr, not going to ask for this to be reopened, but if I may ask, could you please tell me what the issue is or why it's not an issue? Is it expected that CUDA memory usage increases over time, and if so why? And why is the number of subdivisions not reducing the memory footprint? Or is it a known bug in the code? Thanks.

**Comment by jaelim** [comment]
@bruno-ichec for my case, I have many bounding boxes per image. it maybe the reason, but haven't yet to run test with a smaller number of batch size. what's your data look like? could you describe?

**Comment by bruno-ichec** [comment]
@jaelim Biomedical image, with up to a dozen cells scattered on a large image. Smaller batch sizes work, so I can train the network, but it's frustrating that it fits with a larger batch size for over a thousand iterations before not fitting anymore. All I've found that may be related is the following:
https://discuss.pytorch.org/t/cuda-memory-continuously-increases-when-net-images-called-in-every-iteration/501/6

But I'm not sure that's what's happening here, so was hoping for @andy-yun to let me know if that was a known issue, expected behaviour or if there was some configuration I missed.

**Comment by jaelim** [comment]
@bruno-ichec thanks for the link, it helps to understand a possible pinpoint of this problem. I'm attempting to train my model (darknet53.conv.74) with a smaller number of batch size (batch=2, subdivision=2). However, the model training failed to launch (no error. it just printed Done message). I increased the numbers and it seems it runs fine at the smallest of batch=16, subdivision=8. What pre-trained model have you load as your training model?
