### ISSUE TITLE
What is "model.seen" meaning

### ISSUE THREAD

**Issue by yuyijie1995** [andy-yun/pytorch-0.4-yolov3#26]
![image](https://user-images.githubusercontent.com/30818917/46733959-6aaa4480-ccc4-11e8-9b69-b080ccff7092.png)

**Comment by yuyijie1995** [comment]
I don't understand what is it

**Comment by door5719** [comment]
About the training pictures number

**Comment by yuyijie1995** [comment]
Thanks
