### ISSUE TITLE
some simple problems

### ISSUE THREAD

**Issue by door5719** [andy-yun/pytorch-0.4-yolov3#29]
Sir,thank you for your excellent  object about yolo .Great benefits  of studing your object I got. I have some simple problems.
  1.Dose this object needs negative sample?  2.the detect.py resize input picture using cv2.resize to get 416 scale ,this would be make a little difference about  input picture,may be using data augument style(fill with (127,127,127)to maintain the origin pattern) for resizing will peformance better.

**Comment by andy-yun** [comment]
1. nope. 
2. detect.py has similar detect functions. I only modified detect() function. Other functions are not modified to keep the width/height ratio of the input image. The performance is varied along to keeping the aspect ratio or not. Keeping aspect ratio is related to find more accurate bounding box of the object.

**Comment by door5719** [comment]
Thank you sir for your reply and well performance project sharing

**Comment by door5719** [comment]
Thank you sir for your reply and well performance project sharing.
