### ISSUE TITLE
Augmentation

### ISSUE THREAD

**Issue by jaelim** [andy-yun/pytorch-0.4-yolov3#30]
It seems like your code is hard-coded to perform augmentation (crop, scaling, shift, flip, etc) on images by default. So, I am interested in an update to make that as an option, rather than a default feature. Because, some people might want to use a different set of augmentations.

**Comment by CodLiver** [comment]
I think you can fork this project to fix it or pull request it.

**Comment by jaelim** [comment]
@CodLiver Yes, I've already fixed it myself. I'm just suggesting it as a recommendation to the author.

I just tested the stripped version, the performance has significantly gone down. not sure where to start to re-optimize the codes.

**Comment by CodLiver** [comment]
Yeah I can see your point. 

for detect.py: If you use detect_cv2() instead of detect(), the performance is much better. However, I am aware that, PIL has more stuff to do.

**Comment by andy-yun** [comment]
detect_cv2() resize the image to network size without considering aspect ratio. But detect() does.
Keep aspect ratio is related to more accurate bounding box of objects. Therefore, you can select the detection performance or accurate bounding boxes. It's up to you.
