### ISSUE TITLE
images do not match error

### ISSUE THREAD

**Issue by CodLiver** [andy-yun/pytorch-0.4-yolov3#31]
hello I was testing the code and I used a random pictures (sized 400x544px), I got this error. It was working in the previous images. 5 of the labels are correct, but it couldnt write anything.

```
5 box(es) is(are) found
bus: 1.000000
person: 1.000000
car: 0.999882
car: 0.999940
car: 0.988874
Traceback (most recent call last):
  File "detect.py", line 113, in <module>
    detect(cfgfile, weightfile, imgfile)
  File "detect.py", line 39, in detect
    plot_boxes(img, boxes, 'data/predictions1.jpg', class_names)
  File "D:\xx\pytorch-0.4-yolov3\utils.py", line 296, in plot_boxes
    drawtext(img, (x1, y1), text, bgcolor=rgb, font=font)
  File "D:\xx\pytorch-0.4-yolov3\utils.py", line 259, in drawtext
    img.paste(box_img, (pos[0], pos[1]-th-2))
  File "D:\xxx\Anaconda3\lib\site-packages\PIL\Image.py", line 1408, in paste
    self.im.paste(im, box)
ValueError: images do not match
```

**Comment by jaelim** [comment]
@CodLiver Are all your images have same dimensions as mentioned 400x544?

**Comment by CodLiver** [comment]
@CodLiver no, all are different. one is 424x544. The other is 1024x544 etc. The height is same, but width is different. It might be just matrix calc error which is fine. However, just gave for the heads up. The rest of the images are working fine. (w,h) form

**Comment by andy-yun** [comment]
You should check the image mode.
You can convert the image type by the following statements.
Image.open(image_path).convert('RGBA')
or
if image.mode != 'RGBA':
    image = image.convert('RGBA')
