### ISSUE TITLE
problem with cam detection

### ISSUE THREAD

**Issue by amine290** [andy-yun/pytorch-0.4-yolov3#34]
when i try cam detection i get "Unable to open camera"
i tried to dig into the code and found 
    cap = cv2.VideoCapture(1)
    if not cap.isOpened():
        print("Unable to open camera")
        exit(-1)
i dont understand where the problem is 

one more thing i want to train your implimentation to detect melanoma (small object)
i have a good dataset but i am a beginner and i need step by step tutorial to train this implimentation

**Comment by andy-yun** [comment]
Change the camera number to 0. Such as. cap = cv2.VideoCapture(0) because I have two usb cam I use the ‘1’.
In marvis or other yolov2 or yolov3 repository, you can easily found the tutorial.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
