### ISSUE TITLE
yolov3 on coco 

### ISSUE THREAD

**Issue by xiao1228** [andy-yun/pytorch-0.4-yolov3#35]
Hi 
Thank you for the code.
I am just wondering if you could share your results base on your implementation on COCO using yolov3.
Thank you

**Comment by andy-yun** [comment]
It took too much training time, and I did not get 58~9% of original paper even though I made various changes. It has a meaningful value for other data, but the performance is not good for Coco datasets. In the case of Coco data training, I recommend that you should use the original C version.
