### ISSUE TITLE
How can I train model on another image size?

### ISSUE THREAD

**Issue by Oktai15** [andy-yun/pytorch-0.4-yolov3#45]
Great work thanks, @andy-yun!

Can I modify something so that I can train model on images with another shape? In my case, I want to train model on images with 256x256 size

**Comment by andy-yun** [comment]
Sure. You can modify width and height value in cfg file and in get_different_scale of dataset.py, you can modiy 13*20 (in this case you should use 260x260 size) for better training.

**Comment by Oktai15** [comment]
@andy-yun, really, that's it? I didn't see in architecture of model any AdaptiveAveragePooling.. How it works with other image size?

**Comment by andy-yun** [comment]
In the attached image, you can see the stride (red marks in image) to reduce the filters to half. 
By these process, the number of filters decreased. For compatibility to yolov2, I recommend multiples of 13 for image size. 
![image](https://user-images.githubusercontent.com/39820731/50742563-3d801a80-1250-11e9-959d-feb5c18286d4.png)

**Comment by Oktai15** [comment]
Thanks!
