### ISSUE TITLE
Running voc_eval.py gives error

### ISSUE THREAD

**Issue by mahavird** [andy-yun/pytorch-0.4-yolov3#47]
Hi @andy-yun ,

Thanks for the cool repository.

I am facing an issue while validating voc dataset.

What changes do I need to make changes to run the voc_eval.py in python 3.5.

I saw that the code of the file suits the syntax of python 2.7.

Regards,
Mahavir

**Comment by leadcain84** [comment]
there are some mismatch points. 
report the error points.
i will easily change that.

**Comment by mahavird** [comment]
Hi @andy-yun ,

Following is the issue I am facing:
![error](https://user-images.githubusercontent.com/9322397/51040833-82a0a580-15de-11e9-9914-7d7086be918c.png)

**Comment by andy-yun** [comment]
@mahavird 
Use my_eval.py rather than voc_eval.py. voc_eval.py is and old version and it is not used in my repo.

**Comment by mahavird** [comment]
Hi @andy-yun ,

When I tried my_eval.py on my dataset it is giving the following error, which parameters do I need to change ?
![error_new](https://user-images.githubusercontent.com/9322397/51084826-6162c500-1756-11e9-928d-dc0a29837169.png)

As you can see, it is stopping after evaluating a few classes.

**Comment by andy-yun** [comment]
The above error is occurred when the sorted_ind is null. therefore, you can modify the code as:
If len(sorted_ind)>0:
	BB = BB[sorted_ind,:]


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mahavird** [comment]
@andy-yun Thanks for the help. It worked
