### ISSUE TITLE
difference weight file

### ISSUE THREAD

**Issue by mrkieumy** [andy-yun/pytorch-0.4-yolov3#59]
Hi @andy-yun , Sorry I don't understand the difference size of weight file like this:
The original yolov3.weight file from website is 248MB (248007028 bytes)
But after training with this repo, the size of the weight file is: 246 (246305368 bytes). Inside 20 bytes header and 61576342 variables x 4 float bytes.
And the load_weight function also load only 246MB (included header). Darknet too.
Why is the difference? Is it the network load incorrect? And is it effect the training performance?
Thanks.

**Comment by andy-yun** [comment]
@mrkieumy 
That phenomenon is correct. The different size is related to the number of classes in yolo layers.
The number of classes is related to the filter size in the previous layers.

**Comment by mrkieumy** [comment]
ah, I see, thank you very much @andy-yun.
Best regards.
