### ISSUE TITLE
Problem in train.py

### ISSUE THREAD

**Issue by sonal-bansal** [andy-yun/pytorch-0.4-yolov3#6]
hi, While i was running train.py ,I've noticed that my test() isn't being called .I've changed max_epochs to just 2 just for trying .
Moreover , its taking lot of time to run even  1 epoch. Can you help me??

**Comment by sonal-bansal** [comment]
As well as when i'm validating I'm getting this error.(I'm running for VOC)

Traceback (most recent call last):
  File "valid.py", line 85, in <module>
    valid(datacfg, cfgfile, weightfile, outfile)
  File "valid.py", line 43, in valid
    buf = '%s/%s%s.txt' % (prefix, outfile, names[i])
IndexError: list index out of range

**Comment by andy-yun** [comment]
first question:
train.py: 144 lines,
if the epoch is greater than the save_interval, call test(epoch). 
Therefore, if you want to evaluate the model, you should get a cup of coffee and relax.
and if you want to evaluate the model, just use eval.py indeed.

Unfortunately, test() with different model takes a long time at first evalution, but, actually it works correctly. This is the reason that I restricts the test() after save_interval.
Maybe, it calculate all possible connection and weights or some restrictions of GPU computation. 
I didn't know exactly.

**Comment by andy-yun** [comment]
second question: 
trained model and label files are different. For example, the number of classes in trained model is 60, but you inputed the lables as 20. You should prepare the exact matching classes (labels).

**Comment by sonal-bansal** [comment]
Thank you Sir
