### ISSUE TITLE
Dear sir

### ISSUE THREAD

**Issue by a819411321** [andy-yun/pytorch-0.4-yolov3#62]
Thank for your code,I use your code ,but a mistake appear.
Traceback (most recent call last):
  File "train.py", line 375, in <module>
    main()
  File "train.py", line 90, in main
    nsamples = file_lines(trainlist)
  File "/home/zyy/下载/pytorch-0.4-yolov3/utils.py", line 421, in file_lines
    thefile = open(thefilepath, 'rb')
IOError: [Errno 2] No such file or directory: 'coco_train.txt'
 Input :python train.py -d cfg/coco.data -c cfg/yolo_v3.cfg -w yolov3.weights
I have coco.data yolo_v3.cfg  yolov3_weights
But I don't have 'coco_train.txt'
How to get coco_train.txt

**Comment by andy-yun** [comment]
@a819411321 coco_train.txt file is generated from the coco dataset and ground truth information.
You should check https://github.com/pjreddie/darknet/blob/master/cfg/coco.data at pjreddie github.
