### ISSUE TITLE
my_eval.py error

### ISSUE THREAD

**Issue by sdustdk1427** [andy-yun/pytorch-0.4-yolov3#66]
When I run 
$ python scripts/my_eval.py results/comp4_det_test_ 2007_test.txt data/voc.names
it can't get mAP,I just get this 
/public/home/G19850028/RWJ/pytorch-0.4-yolov3-master/VOCdevkit/VOC2007/JPEGImages/000009.jpg 000009
why?what should i do?

**Comment by andy-yun** [comment]
@sdustdk1427 Did you do valid.py before my_eval.py? If you did, I think, your model is not correctly trained.

**Comment by sdustdk1427** [comment]
I find if i delete output file, this problem will be solve.....thanks
