### ISSUE TITLE
 i dont know what is the problem

### ISSUE THREAD

**Issue by vcvishal** [andy-yun/pytorch-0.4-yolov3#70]
when I ran it shows 
C:\Users\vcvis\Desktop\pytorch-0.4-yolov3-master>python train.py -d cfg/voc.data -c cfg/yolo-voc.cfg -w yolov3.weights
Training for (1935,311)
please help 
thank you

**Comment by andy-yun** [comment]
@vcvishal  Try to add -r to the command. yolov3.weights is already trained many epochs. Thus, the training is stopped max epoch is reached. -r means resetting epoch and starts from 0.

**Comment by vcvishal** [comment]
thank you 
it works 
again thank you for code
