### ISSUE TITLE
Why just output "Training for (12801,1285)"??

### ISSUE THREAD

**Issue by yyx1107** [andy-yun/pytorch-0.4-yolov3#73]
When I run "python train.py -d cfg/voc.data -c cfg/yolov3-voc.cfg -w yolov3.weights"
It only outputs "Training for (12801,1285)", and then it ends.
------------------------------------------------
yyx@yyx-PowerEdge-T30:~/Downloads/pytorch-0.4-yolov3-master$ python train.py -d cfg/voc.data -c cfg/yolov3-voc.cfg -w yolov3.weights
Training for (12801,1285)
yyx@yyx-PowerEdge-T30:~/Downloads/pytorch-0.4-yolov3-master$
-------------------------------------------------

**Comment by andy-yun** [comment]
Same phenomenon like #70. 
Add -r option to your command.
