### ISSUE TITLE
Where should I edit code to change input image?

### ISSUE THREAD

**Issue by richard0326** [andy-yun/pytorch-0.4-yolov3#74]
I want to change input image a little. with ground truth value.
I was looking in to the source code. Maybe ' image.py' 'load_data_detection' function could be ok??

but I'm not sure where to edit...
Can you give me a hint??

**Comment by andy-yun** [comment]
@richard0326 in 259th line of image.py:
img = Image.open(imgpath).convert('RGB') # for training
in 67th line of dataset.py when test mode.
same command is used for open images. You can modify the above lines.

**Comment by richard0326** [comment]
Does it work in train as well??

**Comment by andy-yun** [comment]
@richard0326 you should try the codes before the question. Good luck.
