### ISSUE TITLE
find loss each epochs

### ISSUE THREAD

**Issue by richard0326** [andy-yun/pytorch-0.4-yolov3#76]
I want to know loss for each epochs, so I have tried this way.

I saved 'total losses' for each steps and get mean value of it.

I decided as loss for each epochs. But I'm not sure...

I there any other way to find the loss for each epochs??

**Comment by andy-yun** [comment]
@richard0326 you can use tensorboard in pytorch or other tools. You should google it.

**Comment by richard0326** [comment]
thank you! I will try it
