### ISSUE TITLE
What is 'eps' in evalutation?

### ISSUE THREAD

**Issue by richard0326** [andy-yun/pytorch-0.4-yolov3#77]
```
eps           = 1e-5

...

precision = 1.0*correct/(proposals+eps)
recall = 1.0*correct/(total+eps)
fscore = 2.0*precision*recall/(precision+recall+eps)
```

I'm working on understanding the evaluation system. And having problem in understanding eps...
Why do you add '1e-5' value. And named it eps??

**Comment by andy-yun** [comment]
@richard0326 eps stands for epsilon and has a role to avoid divide-by-zero exception.

**Comment by richard0326** [comment]
thank you
