### ISSUE TITLE
Where can i find mAP in code?

### ISSUE THREAD

**Issue by richard0326** [andy-yun/pytorch-0.4-yolov3#78]
I have searched valid.py source code and found this. Not mAP. In example of homepage they return mAP but I couldn't find it.

`fps[cls_id].write('%s %f %f %f %f %f\n' % (fileId, prob, x1, y1, x2, y2))`

return this... not mAP like example.

below is my return.
![1](https://user-images.githubusercontent.com/18134703/59962949-6444bb80-9527-11e9-8e8a-2045319c2ad7.PNG)

**Comment by andy-yun** [comment]
after executing valid.py, you should run my_eval.py for voc_data as:
python scripts/my_eval.py results/comp4_det_test_ data/2007_test.txt data/voc.names

**Comment by richard0326** [comment]
thank you!
