### ISSUE TITLE
embedded null byte

### ISSUE THREAD

**Issue by AmIr-KinG** [andy-yun/pytorch-0.4-yolov3#8]
Hi
I've been struggling with this problem for a while now. When I run train.py file, I face the error "embedded null byte". It seems to happen when the code tries to read images using filenames. Here's the traceback i get.

> Traceback (most recent call last):
>   File "train.py", line 351, in <module>
>     main()
>   File "train.py", line 144, in main
>     nsamples = train(epoch)
>   File "train.py", line 204, in train
>     for batch_idx, (data, target) in enumerate(train_loader):
>   File "/home/amirking/anaconda3/envs/kerasenv/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 264, in next
>     batch = self.collate_fn([self.dataset[i] for i in indices])
>   File "/home/amirking/anaconda3/envs/kerasenv/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 264, in <listcomp>
>     batch = self.collate_fn([self.dataset[i] for i in indices])
>   File "/home/amirking/yolo3/andy/dataset.py", line 62, in getitem
>     __img, label = load_data_detection(imgpath, self.shape, jitter, hue, saturation, exposure)__
>   File "/home/amirking/yolo3/andy/image.py", line 122, in load_data_detection
>     __img = Image.open(imgpath).convert('RGB')__
>   File "/home/amirking/anaconda3/envs/kerasenv/lib/python3.6/site-packages/PIL/Image.py", line 2548, in open
>     fp = builtins.open(filename, "rb")

**Comment by andy-yun** [comment]
You should check your images. Using other tools, you can check the image.
I think your image is corrupted.

**Comment by andy-yun** [comment]
I am sorry I didn't find that case for general usage. But, when I use COCO database, I found that error.
If you use Pillow package than PIL, you can void that image file truncation error by adding the
from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True
But, I am not sure original PIL package can avoid that error by the above sentences.
